### ISSUE TITLE
`make` fails on Python 3.10

### ISSUE THREAD

**Issue by nan-af** [floodlight/loxigen#707]
`make` fails with the following error on Python 3.10:
```
> make
./loxigen.py --install-dir=loxi_output --lang=c --version-list=1.0,1.1,1.2,1.3,1.4
Traceback (most recent call last):
  File "/tmp/loxigen/./loxigen.py", line 81, in <module>
    import cmdline
  File "/tmp/loxigen/cmdline.py", line 30, in <module>
    from loxi_globals import OFVersions
  File "/tmp/loxigen/loxi_globals.py", line 28, in <module>
    from loxi_ir import *
  File "/tmp/loxigen/loxi_ir/__init__.py", line 29, in <module>
    from .ir import *
  File "/tmp/loxigen/loxi_ir/ir.py", line 34, in <module>
    from generic_utils import find, memoize, OrderedSet
  File "/tmp/loxigen/generic_utils.py", line 82, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
make: *** [Makefile:55: .loxi_ts.c] Error 1
```

`generic_utils.py` is attempting to use `MutableSet` from `collections` instead of `collections.abc`.

Importing and using ABCs from `collections` [stopped working in Python 3.10](https://docs.python.org/3/whatsnew/changelog.html#id96) ([bpo-37324](https://bugs.python.org/issue37324)). This had been deprecated since Python 3.3.
